verbose: false # Set to false to disable detailed logs

afk_check:
  placeholder: "%essentials_afk%"
  expected_result: "yes"
  true_message: "&7&o{player} is currently AFK."
  false_message: "disabled" # No false message for this placeholder

#placeholder2:
#  placeholder: "%otherplugin_someplaceholder%"
#  expected_result: "true"
#  true_message: "&a{player} is here!"
#  false_message: "&c{player} is not here." # Set to "disabled" to not send a message on false output